# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='publication date')),
                ('title', models.TextField(verbose_name='news title')),
                ('text', models.TextField(verbose_name='news text')),
                ('short_text', models.CharField(default='No description', max_length=512, verbose_name='news short text')),
                ('image', models.ImageField(default='no_image.jpg', upload_to='news', verbose_name='news image')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='article', verbose_name='news image'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_text',
            field=models.CharField(default='No description', max_length=512, verbose_name='article short text'),
        ),
    ]
