# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170804_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 10, 48, 11, 145003), verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 10, 48, 11, 146863), verbose_name='publication date'),
        ),
    ]
