# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170804_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to=main.models.utils.make_filepath, verbose_name='article image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to=main.models.utils.make_filepath, verbose_name='news image'),
        ),
    ]
