# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170804_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('title', models.TextField(verbose_name='project title')),
                ('text', models.TextField(verbose_name='project text')),
                ('description', models.TextField(default='No description', max_length=256, verbose_name='project description')),
                ('image', models.ImageField(default='no_image.jpg', upload_to=main.models.utils.make_filepath, verbose_name='project image')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(default='No description', max_length=512, verbose_name='news short text'),
        ),
    ]
