# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_indextile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexTile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.FileField(default='no_icon.svg', upload_to=main.models.utils.make_filepath, verbose_name='project icon'),
        ),
    ]
