# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170817_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Tagline title')),
                ('text', models.TextField(verbose_name='Tagline text')),
            ],
        ),
    ]
