# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publication date')),
                ('text', models.TextField(verbose_name='Text under partner')),
                ('link', models.TextField(default='No description', max_length=256, verbose_name='Link to partner')),
                ('icon', models.FileField(default='no_image.png', upload_to=main.models.utils.make_filepath, verbose_name='Partner image')),
            ],
        ),
    ]
