# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(default='/404', verbose_name='project link'),
        ),
    ]
