# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import main.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170826_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('about', models.TextField(verbose_name='About')),
                ('specialty', models.TextField(verbose_name='Specialty')),
                ('image', models.ImageField(default='no_image.png', upload_to=main.models.utils.make_filepath, verbose_name='news image')),
            ],
        ),
    ]
