# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170826_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='chump',
            name='about_short',
            field=models.TextField(default='Good guy and all', max_length=128, verbose_name='Very brief description'),
        ),
    ]
