# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170827_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currentlyRegistered',
            field=models.IntegerField(default=False, editable=False, verbose_name='Currently registered'),
        ),
    ]
