# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models.projects.university_saturdays


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170827_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditory', models.CharField(max_length=30, verbose_name='Auditory')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Event type')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='Subject')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='saturdayRating',
            field=models.IntegerField(default=0, verbose_name='Rating by saturdays'),
        ),
        migrations.AddField(
            model_name='event',
            name='auditory',
            field=models.ManyToManyField(to='main.Auditory', verbose_name='Auditory'),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.ForeignKey(default=main.models.projects.university_saturdays.subject_default, on_delete=django.db.models.deletion.CASCADE, to='main.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(default=main.models.projects.university_saturdays.event_default, on_delete=django.db.models.deletion.CASCADE, to='main.EventType', verbose_name='Event type'),
        ),
    ]
