# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170827_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='chump',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority (optional)'),
        ),
    ]
