# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_chump_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maximum_capacity',
            new_name='maximumCapacity',
        ),
    ]
