# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170827_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='surname',
        ),
        migrations.AddField(
            model_name='pupil',
            name='phone',
            field=models.CharField(default='Nan', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='Grade'),
        ),
    ]
