# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170827_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='chump',
            name='university',
            field=models.TextField(default='ДГУ', verbose_name='University'),
        ),
    ]
