# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_chump_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Event', verbose_name='Event'),
        ),
    ]
