# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_pupil_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isClosed',
            field=models.BooleanField(default=False, verbose_name='Registration closed'),
        ),
    ]
