# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170901_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='types',
        ),
    ]
