# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170901_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
