# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170906_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Event type'),
        ),
    ]
