# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170929_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subject')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('secret', models.CharField(max_length=128, verbose_name='Secret')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('universities', models.ManyToManyField(to='main.University', verbose_name='Universities that he manages')),
            ],
        ),
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Grade'),
        ),
    ]
